name: Reusable workflow with boolean

on:
  workflow_dispatch:
jobs:
  is-true:
      uses: wizlif/test_git_actions/.github/workflows/send-boolean.yml@main
      with:
        COOL_BOOLEAN: true      
  is-false:
      uses: wizlif/test_git_actions/.github/workflows/send-boolean.yml@main
      with:
        COOL_BOOLEAN: false
        